"""Node labels from comments: "Cube" becomes "Cube [Body]".

An assistant that comments its OpenSCAD names every row of the tree;
codegen writes the label back as a trailing comment, so it survives
export -> import.

Copyright (C) 2026 Gwilherm Kerherve

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
"""

import pytest
from PyQt5.QtWidgets import QApplication

from khervecad import scadparse
from khervecad.model import CadNode, DocumentModel, name_tag, with_tag


@pytest.fixture(scope="module")
def app():
    return QApplication.instance() or QApplication([])


def _names(root):
    return [n.name for n in root.walk() if n.type != "root"]


def test_tag_helpers():
    assert name_tag("Cube [Body]") == "Body"
    assert name_tag("Cube") == ""
    assert with_tag("Cube", "Body") == "Cube [Body]"
    assert with_tag("Cube [Body]", "Head") == "Cube [Head]"
    assert with_tag("Cube", "a [b]") == "Cube [a (b)]"


def test_trailing_comment_labels_the_statement():
    root, _ = scadparse.parse_scad(
        "cube([50, 80, 40], center=true);  // Body\n"
        "sphere(5); // Eye\n")
    assert _names(root) == ["Cube [Body]", "Sphere [Eye]"]


def test_trailing_comment_on_a_chain_labels_the_innermost():
    root, _ = scadparse.parse_scad(
        'color("pink") translate([0, 0, 50]) cube(10);  // Head\n')
    color = root.children[0]
    assert color.name == "Color"
    # the translate folds into the cube's own x/y/z
    cubes = [n for n in color.walk() if n.type == "cube"]
    assert [n.name for n in cubes] == ["Cube [Head]"]
    assert all(not name_tag(n.name) for n in color.walk()
               if n.type != "cube")


def test_block_header_comment_labels_the_container():
    root, _ = scadparse.parse_scad(
        "for (i = [0:3]) {  // Legs\n"
        "    translate([i * 10, 0, 0]) cube(5);\n"
        "}\n")
    loop = root.children[0]
    assert loop.type == "for_loop" and name_tag(loop.name) == "Legs"
    assert all(not name_tag(n.name) for n in loop.walk() if n is not loop)


def test_comment_line_above_labels_the_next_statement():
    root, _ = scadparse.parse_scad(
        "// Tail\n"
        "cylinder(h=10, r=1);\n"
        "\n"
        "cube(3);\n")
    assert _names(root) == ["Cylinder [Tail]", "Cube"]


def test_comment_blocks_and_code_name_nothing():
    root, _ = scadparse.parse_scad(
        "// Generated by KherveCAD\n"
        "// Edit objects in the GUI\n"
        "cube(1);\n"
        "// cube([1, 2, 3]);\n"
        "sphere(1);\n"
        "/* Body */ cylinder(h=1, r=1);\n"
        "cube(2); // " + "a very long sentence " * 4 + "\n")
    assert _names(root) == ["Cube", "Sphere", "Cylinder", "Cube"]


def test_module_body_comment_labels_every_call():
    root, _ = scadparse.parse_scad(
        "module leg(x) { translate([x, 0, 0]) cube(5);  // Hoof\n}\n"
        "leg(0);\nleg(10);\n")
    hooves = [n for n in root.walk() if name_tag(n.name) == "Hoof"]
    assert len(hooves) == 2


def test_label_round_trips_through_the_program(app):
    model = DocumentModel()
    color = CadNode("color", "Color", dict(color="red"))
    color.add(CadNode("cube", "Cube [Body]", dict(x=50, y=80, z=40)))
    model.root.add(color)
    code = model.to_scad()
    assert "// Body" in code
    root, _ = scadparse.parse_scad(code)
    assert [n.name for n in root.walk()
            if n.type == "cube"] == ["Cube [Body]"]
    again = DocumentModel()
    again.root = root
    assert again.to_scad() == code


def test_unlabelled_nodes_emit_no_comment(app):
    model = DocumentModel()
    model.root.add(CadNode("cube", "Cube", dict(x=1, y=1, z=1)))
    body = model.to_scad().split("\n", 4)[-1]
    assert "//" not in body
