"""Tests for the object tree model and OpenSCAD code generation.

Run with: python -m pytest tests/  (offscreen Qt).

Copyright (C) 2026 Gwilherm Kerherve

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
"""

import os
import sys
from pathlib import Path

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pytest
from PyQt5.QtWidgets import QApplication

from khervecad import document
from khervecad.model import CadNode, DocumentModel


@pytest.fixture(scope="session")
def app():
    return QApplication.instance() or QApplication([])


@pytest.fixture
def model(app):
    return DocumentModel()


def test_circle_codegen(model):
    model.add_node("circle", dict(x=5.0, y=-3.0, radius=8.0, segments=32))
    code = model.root.to_scad()
    assert code == "translate([5, -3]) circle(r=8, $fn=32);"


def test_rect_codegen(model):
    model.add_node("rect", dict(x=1.5, y=2.0, width=10.0, height=4.0))
    assert model.root.to_scad() == \
        "translate([1.5, 2]) square([10, 4]);"


def test_line_is_hull_of_circles(model):
    model.add_node("line", dict(x1=0.0, y1=0.0, x2=10.0, y2=0.0,
                                width=2.0))
    code = model.root.to_scad()
    assert code.startswith("hull()")
    assert "circle(d=2" in code


def test_hidden_node_gets_disable_modifier(model):
    node = model.add_node("circle")
    model.set_visible(node, False)
    assert model.root.to_scad().startswith("*")


def test_extrude_wraps_children(model):
    circle = model.add_node("circle", dict(x=0.0, y=0.0, radius=5.0,
                                           segments=16))
    model.wrap_nodes([circle], "linear_extrude")
    code = model.root.to_scad()
    assert code.splitlines()[0] == "linear_extrude(height=10) {"
    assert "circle(r=5" in code
    assert code.rstrip().endswith("}")


def test_rotate_extrude_partial_angle(model):
    rect = model.add_node("rect")
    wrapper = model.wrap_nodes([rect], "rotate_extrude")
    wrapper.params["angle"] = 90.0
    assert "rotate_extrude(angle=90" in model.root.to_scad()


def test_difference_order_preserved(model):
    cube = model.add_node("cube")
    sphere = model.add_node("sphere")
    model.wrap_nodes([cube, sphere], "difference")
    code = model.root.to_scad()
    assert code.index("cube") < code.index("sphere")
    assert code.startswith("difference() {")


def test_group_and_ungroup(model):
    a = model.add_node("circle")
    b = model.add_node("rect")
    group = model.group_nodes([a, b])
    assert group.type == "union"
    assert len(model.root.children) == 1
    model.ungroup(group)
    assert [n.type for n in model.root.children] == ["circle", "rect"]


def test_wrap_refuses_orphan(model):
    node = CadNode("circle")
    assert model.wrap_nodes([node], "union") is None


def test_move_refuses_own_descendant(model):
    a = model.add_node("union")
    b = model.add_node("circle", parent=a)
    model.move_node(a, b)               # must be a no-op
    assert a.parent is model.root
    assert b.parent is a


def test_duplicate_deep_copies(model):
    group = model.add_node("union")
    model.add_node("circle", dict(radius=7.0), parent=group)
    clone = model.duplicate(group)
    assert clone is not group
    assert clone.children[0].params["radius"] == 7.0
    clone.children[0].params["radius"] = 9.0
    assert group.children[0].params["radius"] == 7.0


def test_unique_names(model):
    a = model.add_node("circle")
    b = model.add_node("circle")
    assert a.name != b.name


def test_text_escaping(model):
    model.add_node("text", dict(text='say "hi"\\'))
    code = model.root.to_scad()
    assert '\\"hi\\"' in code


def test_has_2d_content(model):
    circle = model.add_node("circle")
    wrapper = model.wrap_nodes([circle], "linear_extrude")
    assert wrapper.has_2d_content()
    cube = model.add_node("cube")
    assert not cube.has_2d_content()


def test_program_header(model):
    assert model.to_scad().startswith("// Generated by KherveCAD")


def test_kcad_roundtrip(model, tmp_path):
    circle = model.add_node("circle", dict(x=3.0, y=4.0, radius=6.0))
    model.set_visible(circle, False)
    ext = model.wrap_nodes([circle], "linear_extrude")
    ext.params["twist"] = 45.0
    model.add_node("cube", dict(width=5.0))

    path = tmp_path / "doc.kcad"
    document.save_kcad(model, str(path))

    other = DocumentModel()
    document.load_kcad(other, str(path))

    assert len(other.root.children) == 2
    loaded_ext = other.root.children[0]
    assert loaded_ext.type == "linear_extrude"
    assert loaded_ext.params["twist"] == 45.0
    loaded_circle = loaded_ext.children[0]
    assert loaded_circle.visible is False
    assert loaded_circle.params["radius"] == 6.0
    assert other.root.to_scad() == model.root.to_scad()


def test_kcad_rejects_foreign_json(model, tmp_path):
    path = tmp_path / "bad.kcad"
    path.write_text('{"format": "other"}')
    with pytest.raises(ValueError):
        document.load_kcad(model, str(path))


def test_export_scad(model, tmp_path):
    model.add_node("sphere")
    out = tmp_path / "out.scad"
    document.export_scad(model, str(out))
    assert "sphere(r=12" in out.read_text()
